apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-qa-validadorcpf
spec:
  type: NodePort
  selector: 
    app: label-pod-helton-qa-validadorcpf
  ports:
    - port: 8001
      nodePort: 30011