apiVersion: v1
kind: Pod
metadata:
  name: helton-qa-validadorcpf
  labels:
    app: label-pod-helton-prod-validadorcpf
spec:
  containers:
    - name: pod-prod-java
      image: heltonscampos/validadorcpf-concrete
      ports:
        - containerPort: 8081